name: PR Comment Action
on:
  issue_comment:
    types:
      - created

jobs:
  pr_commented:

    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Run your action
        run: |
          python main.py
        