name: PR Comment Action
on: [push, pull_request_review, pull_request_review_comment,  issue_comment]
    # types:
    #   - created

jobs:
  pr_commented:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0

      - name: Run your action
        run: |
          python main.py
        
      - name: print current branch
        run: |
          echo "Source branch: ${{ github.ref}}"