name: PR Comment Action
on:
  issue_comment:
    types:
      - created
  push:
    branches:
      - master

jobs:
  pr_commented:

    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0

      - name: Run your action
        run: |
          python main.py
        
      - name: print current branch
        run: |
          echo ${{ github.ref }}