name: First action
on: workflow_dispatch
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "helloooooooo"
      - name: print be lo
        run: echo "beeeee loooooo"
